version: '3.7'
services:
  django-tutorial:
    container_name: django
    image: mzaygar034/django:v1
    restart: always
    environment:
      ALLOWED_HOSTS: "*"
      HOST: mariadb
      USUARIO: django
      CONTRA: django
      BASE_DATOS: django
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.org
    ports:
      - 8088:8003
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: django
    volumes:
      - mariadb:/var/lib/mysql
volumes:
    mariadb:
